services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql;Database=WebShopSQL;User=sa;Password=Password123;Encrypt=False;TrustServerCertificate=True;
    depends_on:
      - sql

  sql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
     - sql
    entrypoint: ["dotnet", "ef", "database", "update"]


volumes:
  sql_data:
